<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetCoreAppCurrent)-windows;$(NetCoreAppCurrent)-linux;$(NetCoreAppCurrent)-osx</TargetFrameworks>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(CommonTestPath)System\Net\Http\VariableLengthIntegerHelper.cs" Link="Common\System\Net\Http\VariableLengthIntegerHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="WebTransportTestBase.cs" />
    <Compile Include="WebTransportSessionCreationOptionsTests.cs" />
    <Compile Include="WebTransportPlatformDetectionTests.cs" />
    <Compile Include="ClientWebTransportSessionTests.cs" />
  </ItemGroup>

</Project>
